name: Expandable
description: Expand properties with values
author: https://github.com/xwlee
requirements:
  - docker
configuration:
  properties:
    files:
      type: array
    directories:
      type: array
    properties:
      type: object
  required: []
